### ISSUE TITLE
Including (use) namespace doesn't work on Interfaces

### ISSUE THREAD

**Issue by danielgelling** [gl3n/sublime-php-namespace#14]
When creating a class that implements a contract, pressing alt+u doesn't include (use) the contract but includes the class itself instead.

**Comment by woecifaun** [comment]
Hi, @danielgelling 

This is how I understand the _alt+u_ command: it generates the `use` statement for your current file. If you're in a `class` file, it generates the `use` for the current class either it extends another one or implements an interface. If you're in `interface` file, it generates the `use` statement for the current interface so you can just copy it and paste it in the class implementing it.

If I'm correct on the author's intentions then I think your issue can be closed.
