### ISSUE TITLE
Got PB With blocnote

### ISSUE THREAD

**Issue by wrossier** [gl3n/sublime-php-namespace#15]
Hello,

**Comment by dlasserre** [comment]
+1 bullshit

**Comment by wrossier** [comment]
thanks @dlasserre

**Comment by dlasserre** [comment]
.s$$$s.
              $$$$$$$$s.
             $$$' $$`$$$s
            $$; ~ $$~`$;$
            $;$ o> $o  $$;
           `;$$$  .\s.,$$,
           ;$$$\`-=-  /$;`
             '' |.__,||
                |    '|=-.__
           ,-=-';`    |     `.
          (          /|       \
           :      ,   ;   |\   \
           ;             :; `.  \
          :o)  ; :  (o  ;:    \  \
      ,---`.__    `.__,' |     \/ }
      | }-'" |         / |     ; /
      "\U)   |         / ;    / /
        ^\   | :        :_,-='_;
          \  ;          c,__V`
           \/     .     /:
           ;\          / \
          :  \`*=---=*/   :
          |   \Wild~@/     :
          ;    \Love/      `
         /      >-./        `
        /       /  `.        \
       /      ,'     `.       \
      :      /         `.      \
     ;      /            `.     \
    {  )   /               `.    `.
    ;    ,'                  \ \ \ \
   |    :                     `.    \
   :    |                       \    \
  :     |                        \    \
  |     |                         \    \
  |     :                          `.   :
  |    :                             \   :
  |    ;                              \  :
  :   /                                \ ,]
  [==:                                 :=="\
  |   `),                              | \  \
  t-+=y"                               `. +<>
  | [ |                                  | \ \
  |_| |                             osfa |\ \ \
