### ISSUE TITLE
Replace existing namespace statement if exists on php_namespace_insert_namespace command

### ISSUE THREAD

**Issue by gl3n** [gl3n/sublime-php-namespace#3]
When using `php_namespace_insert_namespace` command, check if a namespace statement already exists and if so : replace it.

**Comment by jum4** [comment]
This feature was added in https://github.com/gl3n/sublime-php-namespace/commit/70420c06887410db57cd860346d7b0d3f473fa82

**Comment by ctf0** [comment]
this is not the case on ST3 ,currently it will just replace the whole line like

```
<?php namespace A\B\C;
```

and add the new namespace

**Comment by gl3n** [comment]
Your `namespace ...` statement must be on a different line, under `<?php`

**Comment by ctf0** [comment]
actually what happens is if there is no namespace already declared the plugin will declare a new one and put it right next to the `<?php` but if there is it will simply replace the whole line as mentioned above.
